"""initial schema

Revision ID: 22b08eb64bc5
Revises: 
Create Date: 2026-09-18 17:33:19.451562
"""

from collections.abc import Sequence

import sqlalchemy as sa

# Autogenerate renders custom column types by their full path, so this import is what
# keeps `price_tracker.db.models.UtcDateTime(...)` in a migration from being a NameError.
# It is unused in migrations that touch no timestamp; ruff is told so on the line itself.
import price_tracker.db.models  # noqa: F401
from alembic import op

revision: str = '22b08eb64bc5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_price_cents', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', price_tracker.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'retired', name='productstatus', native_enum=False, create_constraint=True, length=16), server_default='active', nullable=False),
    sa.Column('created_at', price_tracker.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('store', 'external_id', name='uq_products_store_external_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_status_last_checked_at', ['status', 'last_checked_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', price_tracker.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('checked_at', price_tracker.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_history_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_product_id_checked_at', ['product_id', 'checked_at'], unique=False)

    op.create_table('trackings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('target_price_cents', sa.Integer(), nullable=False),
    sa.Column('last_alerted_price_cents', sa.Integer(), nullable=True),
    sa.Column('last_alerted_at', price_tracker.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', price_tracker.db.models.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_trackings_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trackings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trackings')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_trackings_user_id_product_id')
    )
    with op.batch_alter_table('trackings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trackings_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trackings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trackings_user_id'))
        batch_op.drop_index(batch_op.f('ix_trackings_product_id'))

    op.drop_table('trackings')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_product_id_checked_at')

    op.drop_table('price_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_status_last_checked_at')

    op.drop_table('products')
    # ### end Alembic commands ###
